version: "3.9"
services:
 database:
  container_name: database
  image: postgres:13
  environment:
   - POSTGRES_PASSWORD=password
  networks:
   - def
 web:
  container_name: app
  build: .
  ports:
   - 15433:80
  depends_on:
   - database
  networks:
   - def
networks:
  def:
   driver: bridge